eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
server:
  port: 8092
  max-http-header-size: 4048576
spring:
  application:
    name: front-comsumer
#熔断器
feign:
  hystrix:
    endbled: true

    thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html

